import React from 'react';

import {Container, Row, Col, Image} from "react-bootstrap";

const NotFoundModal = () => {
    return (
        <Container>
            Aasdaffas
            1
            2
            3
            4
            5asd
            6
            7
            8
            9
            10
            aaaaaaaaaaa
            16
            17
            18asd
            19
            20
                AB
                1
                2
                3
                4
                5
                6
                7
                8asd
                9
                10
                bbbbbb
                16
                17
                18
                19
                20
                Aasd
                1
                2
                3
                4
                5
                6
                7asd
                8
                9
                10
                aaaaaaaaaaa
                16
                17
                18
                19
                20
                21
                A
                1
                2
                3
                4
                5
                6
                7
                8
                9
                10
                11 12 13 14 15
                16
                17asd
                18
                19
                20
        </Container>
    );
}